actions updates

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,14 +11,41 @@ on:
         type: string
 
 permissions:
-  contents: read
+  contents: write    # Needed for tag creation
   packages: write
 
 jobs:
+  require-tag:
+    if: github.event_name == 'workflow_dispatch'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if manual run without tag
+        run: |
+          if [[ -z "${{ inputs.tag }}" ]]; then
+            echo "❌ The 'tag' input is required for manual deployment.";
+            exit 1
+          fi
+
+  create-tag-on-release:
+    if: github.event_name == 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Create tag for release
+        env:
+          VERSION: ${{ github.event.release.tag_name }}
+        run: |
+          git fetch --tags
+          git tag "${VERSION}"
+          git push origin "${VERSION}"
+
   build-and-push:
+    needs: [require-tag]
+    if: always()
     runs-on: ubuntu-latest
     strategy:
-      fail-fast: false
+      fail-fast: true
       matrix:
         image: [backend, frontend]
     steps:
